### PR TITLE
TRORS Encounter Cards

### PR DESCRIPTION
**Pull request by wargfn**
Setup for the Rise of the Red Skull encounter cards.

### CODE REVIEW

**Comment by Kamalisk** [comment]
so even though it doesn't matter technically, we prefer to split the "encounter" cards into a seperate file from regular player cards. So you need to make a trors_encounter.json file for the encounter cards.

**Comment by wargfn** [comment]
Okay, easily enough done. I will revert this file and add the encounters one.

**Comment by wargfn** [comment]
Edited commit and ready for pull.. Validate.py also doesn't seem to be working.
**Validation error in pack: (code: 'trors' name: 'The Rise of Red Skull')
Additional properties are not allowed (u'pack_type_code' was unexpected)**
Validation error in pack: (code: 'toafk' name: 'The Once and Future Kang')
Additional properties are not allowed (u'pack_type_code' was unexpected)
Validation error in pack: (code: 'ant' name: 'Ant-man')
Additional properties are not allowed (u'pack_type_code' was unexpected)
Validation error in pack: (code: 'wsp' name: 'Wasp')
Additional properties are not allowed (u'pack_type_code' was unexpected)
Validation error in pack: (code: 'qsv' name: 'Quicksilver')
Additional properties are not allowed (u'pack_type_code' was unexpected)
Validation error in pack: (code: 'scw' name: 'Scarlet Witch')
Additional properties are not allowed (u'pack_type_code' was unexpected)
Skipping card validation...
Found 0 formatting and 16 validation errors

**Comment by rdonnelly** [comment]
FWIW, @wargfn, I just put in a PR to update the validation script for the repo (#69). This would probably be helpful to your work here. I, for one, really appreciate the data entry! Nice work!

**Comment by Kamalisk** [comment]
So for linked cards, they need to be a separate entry, and the linked card field just points to the code of the linked card. 

Also most fields are not required, so no need to have lots of fields set to false for cards that don't have those fields.

**Comment by wargfn** [comment]
Great, I will adjust and reply back. Thanks for waiting 30 days to look at
the updates.

**Comment by Kamalisk** [comment]
I very much appreciate the work to put this data in. Sorry I did not look at it sooner, but I have been very busy and encounter cards are a nice to have, rather than a requirement for deck building, so I never got around to looking at this.

**Comment by wargfn** [comment]
I updated, will you check it and see if everything looks good?

**Comment by Kamalisk** [comment]
Seems fine, will try to get it tested this week. Not sure how well it will handle 3 sided cards, so might have to just end up having two sides for ant-man and wasp.

Do we know the exact quantities for ant-man and wasps cards in their hero cards?

**Comment by rdonnelly** [comment]
I _may_ be complicating things, but I think it would make sense to close this PR and take a look at #70. That PR includes all of @wargfn's work (including the change to `back_link`) and some formatting updates/fixes. Let me know if y'all have any questions, happy to address.

**Comment by wargfn** [comment]
Going to close this pull request to allow @rdonnelly change to be pushed in. I will resync after his commit.

**Comment by wargfn** [comment]
Going to close out my pull request so poul #70 can go in. I will resync
after pull#70 is committed.

**Pull request closed without merging**
