### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by Daedalica**
Fully translated player cards and champion encounters.

### CODE REVIEW

**Comment by Daedalica** [comment]
Could use some help here. I dont find the error. 

I created the files and then edited them in the same request. Could this be the error? :S

**Comment by Kamalisk** [comment]
/home/runner/work/marvelsdb-json-data/marvelsdb-json-data/translations/de/pack/thor.json: File is not valid JSON.
Expecting ',' delimiter: line 36 column 62 (char 1662)

**Comment by Kamalisk** [comment]
you can click the details on the validate error, and can then see what error the validator reported.

**Comment by Daedalica** [comment]
Ah thanks, the X was only on file "trors,json", so I only checked this. But now I get some errors with cards for the new "war machine"-pack, I didn't touched.

**Comment by Kamalisk** [comment]
I think you need to rebase against the main branch to get the trait corrections.

**Comment by Daedalica** [comment]
Thanks for your help. I think I understand the problem. But couldn't fix it the "right" way. I just opened a new branch and copy-pasted my changes and it worked. Thank you again!

**Pull request closed without merging**
