### PR TITLE
Add  : OCTGN_ID for Drax and Venom + Encounter cards for Drax/Venom/GMW

### PR DESCRIPTION
**Pull request by Ouroboros009**
Hi! I used add_octgnid.py script for this. I checked every line. Thanks.

### CODE REVIEW

**Comment by Ouroboros009** [comment]
Hi! try to do things the best I can. Hope there is no problem. I'll change anything if I've done any mistake. Thanks!

**Comment by Kamalisk** [comment]
If you can contribute the encounter cards for GMW that would be great.

Of note, try to stick the same indentation in the files where possible (ideally use tabs) but I am not 100% sure what the default is. But if the file has the indenation all changed it is harder to merge the changes.

**Comment by Ouroboros009** [comment]
> 
> 
> If you can contribute the encounter cards for GMW that would be great.
> 
> Of note, try to stick the same indentation in the files where possible (ideally use tabs) but I am not 100% sure what the default is. But if the file has the indenation all changed it is harder to merge the changes.

Not quite sure, did you notice something wrong in indentation in my file ?

**Comment by Kamalisk** [comment]
In the drax file, you replaced all the tabs with spaces, so it shows up as the whole file being changed. I can view changes ignoring whitespace changes, but it just takes more effort. Whatever editor you are using should let you change them easily from one to another.

**Comment by Ouroboros009** [comment]
> 
> 
> In the drax file, you replaced all the tabs with spaces, so it shows up as the whole file being changed. I can view changes ignoring whitespace changes, but it just takes more effort. Whatever editor you are using should let you change them easily from one to another.

ok, not quite use to that. I update them, it should be better now.

**Comment by Ouroboros009** [comment]
Did my best to contribute! Used validate.py and it's seems ok. Thanks!

**Comment by Kamalisk** [comment]
Thanks again for this, I merged and it is mostly great.

Schemes require threat and base_threat set on them (even if you just set it to 0), so I did that myself (I should add it to the validator so it shows you)

In addition, when you add new card sets (e.g. the modular sets) you need to add the code to sets.json along with the name (I did that myself too)
You can see the changes in the commit I just made.

**Pull request merged**
