### PR TITLE
fix duplicates

### PR DESCRIPTION
**Pull request by mmougy**
When editing deck, cards duplicate shouldn't be displayed

image

### CODE REVIEW

**Comment by jordanweiler** [comment]
I think it's worth discussing if this is the desired outcome.

The X-Men cards have different artwork (something about licensing where the X-Men waves needed to reprint any previous cards with different X-Men specific artwork). You'll notice this with the basic resource cards and other faction specific cards. There is also different flavor text and illustrators on these cards.

If we are going to consider these the same cards as the original artwork cards then it might cause confusion when someone looks at the photo in marvelcbd and notices that their card doesn't match it. The downside is that multiple versions of the card can show up in deckbuilding.

This could easily be a long term issue with different waves reprinting with other artwork too. I'm curious what @Kamalisk thinks about whether this is an issue to fix and if so how.

**Comment by jordanweiler** [comment]
> Imo it is better to avoid duplicate lines in the deckbuilding section.
> Currently basic resource with multiple art doesn't show up twice in the deckbuilding section.

I'm not disagreeing that ideally the deckbuilding section only shows a card with multiple versions once. I think that would be the best user experience and prevent users from breaking deckbuilding rules by selecting 3 Endurance cards from Ms. Marvel and 3 from Storm (for example) because they have different artwork, etc. It looks like the new X-Men resource cards were marked as duplicates of the original resource cards so we never got new versions of those cards to clash with the originals. I agree that whatever is decided for cards with new artwork/flavor/illustrators/text should be consistent throughout the database.

I think solving this by marking them all as duplicates of the original card is incorrect though. That's an over simplified solution that loses metadata about the newer cards. These really seem like different versions of cards and some users might have one and not the other so I don't think treating the first version as king is accurate for all users. There's also the possibility that the same card might be reprinted with updated text in the future (this happens in Arkham but I don't think this has happened in Marvel Champions yet) so we might want to create a solution that can handle that type of versioning elegantly to solve our current problem but also handle future variations.

I think we'll likely need changes in the marvelsdb repo as well as here to solve this correctly but I am curious about what @Kamalisk thinks. Instead of using `duplicate_of` maybe we need something like `version_of`/`new_version_of`/`alternate_of`. The tricky part will be displaying this type of information elegantly when deckbuilding.

**Comment by Kamalisk** [comment]
duplicate of is meant for this purpoe. While it currently doesn't support it could have some specfic information that is different (e.g. artist) as the art is different. Both cards exist in the system when flagged as duplicate, so a user can add one or the other to their collection and see both cards. However the deck builder only shows one card (it should show the duplicate if you dont own the original, though for practical purposes you wont notice). Marking it as a duplicate ensures the text remains the same if you update the originals.

**Comment by jordanweiler** [comment]
So sounds like when we mark these different artwork cards as duplicate we need to keep the properties that are different so that we can display those differences if needed. I think `flavor` and `illustrator` are the only ones currently that are different.

**Pull request merged**
