### PR TITLE
Added the nemesis cards for Groot and Rocket Raccoon

### PR DESCRIPTION
**Pull request by q3c0**

### CODE REVIEW

**Comment by q3c0** [comment]
For this one, the scheme_amplify was added for the Vendetta side scheme. Hope it is ok!

**Comment by Kamalisk** [comment]
thanks for doing these. The extra json field might not work until I have added support for it, but I am fine with the field name you chose. Might not get around to merging these yet but will do so when I can.

**Comment by q3c0** [comment]
Thanks @Kamalisk!

May I ask some suggestions on if this is the correct way to work? Since I'm trying to also help out on the OCTGN plugin, at the moment I am keeping different branches for the different heroes and sets, merging them together in a completely separate branch (dev). In this way your job should be a little easier as any mistake (Like a typo on a card) can be fixed in its own branch, then merged on my dev branch.

Sorry if it is a noob question, possibly a PR is not the best way to publish it, but I'd like to ask directly to the one receiving the PR, as I'm still not too familiar with distributed version control :D

**Comment by Kamalisk** [comment]
I did the player cards and the encounter cards are a nice to have but my time is limited, so I tend to stick to things needed for deck building. So happy to have someone else help with the encounter cards so the database can be complete. 
I definitely don't add octgn ids so whomever wants them added needs to do what you did, so feel free to keep doing it all.

Making pull requests is definitely the right way to do it, and splitting them up helps immensely as an error in one doesn't hold up the others.

**Comment by q3c0** [comment]
Do you know if someone is working on the encounters for GMW?

**Comment by Kamalisk** [comment]
not to my knowledge.

**Comment by Ouroboros009** [comment]
> 
> 
> Do you know if someone is working on the encounters for GMW?

hi! I've done it to implement them in OCTGN but still missing text and flavor for now. Do you want us to share the work ?

**Pull request merged**
