### PR TITLE
Spoiled cards from Spider-Ham and SP//dr

### PR DESCRIPTION
**Pull request by fafranco82**

### CODE REVIEW

**Comment by Kamalisk** [comment]
Do we have all of their hero cards yet? (due to the way the system works, a hero needs all their cards before I can add the hero)

Thanks for even adding the colors =)

**Comment by fafranco82** [comment]
Ah! No, they don't. But now the work is half done... I will be adding more commits as the spoilers appears, and when the hero have all of his cards spoiled, I will notice you here ;)

**Comment by Ouroboros009** [comment]
> Ah! No, they don't. But now the work is half done... I will be adding more commits as the spoilers appears, and when the hero have all of his cards spoiled, I will notice you here ;)

Hi! Thanks for this! All cards spoiled today. Can you also add octgn_id to every cards ?

**Comment by fafranco82** [comment]
Sure!

**Comment by fafranco82** [comment]
Packs completed.

@Ouroboros009 where I can find the OCTGN ids for cards and sets? I wanted to extract from [this repo](https://github.com/twistedsistem/OCTGN-Marvel-Champions) I found, but has no info yet about the last two packs.

**Comment by Ouroboros009** [comment]
> Packs completed.
> 
> @Ouroboros009 where I can find the OCTGN ids for cards and sets? I wanted to extract from [this repo](https://github.com/twistedsistem/OCTGN-Marvel-Champions) I found, but has no info yet about the last two packs.

I didn't push them to the repo. I'll send you all of them.

**Comment by Ouroboros009** [comment]
> Packs completed.
> 
> @Ouroboros009 where I can find the OCTGN ids for cards and sets? I wanted to extract from [this repo](https://github.com/twistedsistem/OCTGN-Marvel-Champions) I found, but has no info yet about the last two packs.
[packs.zip](https://github.com/zzorba/marvelsdb-json-data/files/9087622/packs.zip)
I don't know if I can commit to your pull request or didn't find how to so I send a zip file containing all modified .json

**Comment by fafranco82** [comment]
Files unpacked directly in my PR :)

**Comment by Kamalisk** [comment]
Thanks a lot for these. Had to some weirdness for Sp//der due to having two cards for their ID (similar to ironheart)
Though I don't know why they didnt just have the hero and alter-ego on the same card, and have the permanent flip when she flips.

**Comment by fafranco82** [comment]
> Thanks a lot for these.

You're welcome!! I'm simply tired of translating nothing to Spanish, so I decided to add the English version, too, hehehe

> Had to some weirdness for Sp//der due to having two cards for their ID (similar to ironheart) Though I don't know why they didnt just have the hero and alter-ego on the same card, and have the permanent flip when she flips.

That's the same I thought about it...

**Pull request merged**
