### PR TITLE
War Machine nemesis set / Valkyrie set (no text) / OCTGN ID

### PR DESCRIPTION
**Pull request by Ouroboros009**
Added The Hood and Valkyrie in sets.json too.

### CODE REVIEW

**Comment by Ouroboros009** [comment]
Hope it helps a bit. Tell me if there is anything I need to fix.

**Comment by Kamalisk** [comment]
thanks a lot. Definitely helps a lot =)

THe main issue is that main schemes should be set to double_sided and use back_text and back_flavor etc.. rather than using the back_link. The back_link is for cards with different types on each side (and when using that, should NOT set double_sided at all)
This is for the hood pack,.

**Comment by Ouroboros009** [comment]
> thanks a lot. Definitely helps a lot =)
> 
> THe main issue is that main schemes should be set to double_sided and use back_text and back_flavor etc.. rather than using the back_link. The back_link is for cards with different types on each side (and when using that, should NOT set double_sided at all) This is for the hood pack,.

Thanks for your feedback. I fixed hood pack and Valkyrie hero card. I'm still not sure how I should consider the "Formidable Foe" card (24049) as it's a double sided card with same type on both but not exactly same (one for standard and one for expert).

**Comment by fdutreux** [comment]
Hi there thanks for your work, just a thing, it seems that the resources types are missing for the Valkyrie pack ("resource_energy": 1, etc)

**Comment by Ouroboros009** [comment]
> Hi there thanks for your work, just a thing, it seems that the resources types are missing for the Valkyrie pack ("resource_energy": 1, etc)

That's right. I've updated pack a few minutes ago.

**Comment by Kamalisk** [comment]
> > thanks a lot. Definitely helps a lot =)
> > THe main issue is that main schemes should be set to double_sided and use back_text and back_flavor etc.. rather than using the back_link. The back_link is for cards with different types on each side (and when using that, should NOT set double_sided at all) This is for the hood pack,.
> 
> Thanks for your feedback. I fixed hood pack and Valkyrie hero card. I'm still not sure how I should consider the "Formidable Foe" card (24049) as it's a double sided card with same type on both but not exactly same (one for standard and one for expert).

For cards with the same type on both sides, use doubled_sided, then set the back_flavor, back_text and back_title for the side that is different. (I think there is also back_traits)

**Comment by Kamalisk** [comment]
I merged this and fixed the last few issues myself.

FYI: 
The Valkyrie hero card needed to not be set to double_sided as it was using a "back_link". The alter-ego was missing health (even though its the same as the hero it is considered a seperate alter-ego card)

The hood had the wrong set name (should have been "the_hood") and you re-used the wrecking_crew set name, as that was used for the original encounter pack of The Wrecking Crew, so I renamed the new one to wrecking_crew_modular. 

Thanks again for the help.

**Pull request merged**
