### PR TITLE
Add NeXt Evolution campaign box

### PR DESCRIPTION
**Pull request by jordanweiler**
This includes the new NeXt Evolution campaign box that is scheduled to be released on 2023-08-18. One of the fun things about this new campaign box (besides all the new awesome heroes/allies/villains/minions) is that a new `player_side_scheme` card type is being released. I've already created a PR in the marvelsdb repo (https://github.com/zzorba/marvelsdb/pull/184) that allows these new cards to be added to decks.

### CODE REVIEW

**Comment by Ouroboros009** [comment]
> **NOTE: Leaving this as a DRAFT until the rest of the cards are announced/released.**
> 
> This includes the new NeXt Evolution campaign box that is scheduled to be released on 2023-08-18. One of the fun things about this new campaign box (besides all the new awesome heroes/allies/villains/minions) is that a new `player_side_scheme` card type is being released. I've already created a PR in the marvelsdb repo ([zzorba/marvelsdb#184](https://github.com/zzorba/marvelsdb/pull/184)) that allows these new cards to be added to decks.

Thanks for your help. I've pulled a request just now to change the way octgn id are generated. If you happen to complete this box or other releases, please check on the new version of add_octgnid.py so it would make my life easier to keep octgn module up-to-date. Sorry, i'm not english native so I hope it was clear enough. Let me know if you need more info.

**Comment by jordanweiler** [comment]
> Thanks for your help. I've pulled a request just now to change the way octgn id are generated. If you happen to complete this box or other releases, please check on the new version of add_octgnid.py so it would make my life easier to keep octgn module up-to-date. Sorry, i'm not english native so I hope it was clear enough. Let me know if you need more info.

Yes, if your PR gets merged before this one is ready (I'm assuming this won't be fully ready until July/August depending on when the full set is leaked), I can definitely merge that code in and re-run the calculations for the octgn values to get the new format you created.

**Comment by jordanweiler** [comment]
This currently contains all the cards for Cable and Domino. I'm still working on all the encounter cards and campaign cards since there are so many of them and I haven't been able to find images of all the cards yet. If we want to merge this early to allow users to start creating decks with those new heroes, I've verified I can successfully create Cable and Domino decks locally and I can create a follow-up PR to add the rest of the encounter/campaign cards. Otherwise, I'll keep pushing new cards to this PR.

**Comment by Kamalisk** [comment]
nice thanks. gonna test it today and get it live.

**Pull request merged**
