### PR TITLE
All captain america cards

### PR DESCRIPTION
**Pull request by zzorba**

### CODE REVIEW

**Comment by zzorba** [comment]
Typed up the Cap cards, since we now know all cards, positions, and quantities.

**Comment by Kamalisk** [comment]
are these 100% confirmed? have the numbers been read correctly? :P

**Comment by zzorba** [comment]
Pretty sure... the scans were MUCH better than the previous ones.
https://www.reddit.com/r/marvelchampionslcg/comments/e0wp0p/every_captain_america_signature_card_revealed_so/

Let me read through them once more tomorrow just to triple check.

**Comment by zzorba** [comment]
Okay, reconfirmed based on pictures from reddit.  The set positions + card numbers line up, so I think these are all correct.

**Pull request merged**
